# Generated by Django 3.2.13 on 2022-06-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20220606_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalAmount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalPayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('member', models.CharField(blank=True, max_length=100, null=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
