# Generated by Django 3.2.13 on 2022-06-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_totalamount_totalpayments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalAmount',
        ),
    ]
