# Generated by Django 3.2.13 on 2022-06-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_delete_totalamount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalPayments',
        ),
    ]
