# Generated by Django 3.2.13 on 2022-09-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_nameken'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameken',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
