# Generated by Django 3.2.13 on 2022-11-12 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='memberdetails',
            name='password',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='account_name',
            field=models.CharField(default='Demo Account', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='branch',
            field=models.CharField(default='Main', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='expiry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='pid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='account_name',
            field=models.CharField(default='Demo Account', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='branch',
            field=models.CharField(default='Main', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='pid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='email',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='password',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
