# Generated by Django 3.2.13 on 2022-11-17 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20221112_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdetails',
            name='pid',
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='email',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='expiry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='mid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='password',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memberdetails',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
