# Generated by Django 3.2.13 on 2022-12-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20221117_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='fullname',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
