# Generated by Django 3.2.13 on 2023-03-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20221209_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='access',
            field=models.CharField(default='Limited', max_length=200, null=True),
        ),
    ]
