# Generated by Django 3.2.13 on 2023-03-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_clientdetails_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='access',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='unlimited',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
