# Generated by Django 3.2.13 on 2023-03-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_clientdetails_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogDetails',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='session_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
