# Generated by Django 3.2.13 on 2022-06-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0053_auto_20220606_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sms', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('audio_file', models.FileField(blank=True, default='', null=True, upload_to='audio-uploads/')),
                ('contact', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
