# Generated by Django 3.2.13 on 2022-06-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0055_messages_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignpaymentduration',
            name='expiration_bill',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
