# Generated by Django 3.2.13 on 2022-06-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0056_assignpaymentduration_expiration_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignpaymentduration',
            name='total_invoices',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
