# Generated by Django 3.2.13 on 2022-06-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0059_totalamount_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalpayments',
            name='member',
            field=models.CharField(default='Gideon K. Impraim', max_length=100, null=True),
        ),
    ]
