# Generated by Django 3.2.13 on 2022-06-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0060_totalpayments_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
