# Generated by Django 3.2.13 on 2022-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0062_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignpaymentduration',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='assignpaymentduration',
            name='total_invoices',
        ),
        migrations.AddField(
            model_name='assignpaymentduration',
            name='amount_by_days',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
