# Generated by Django 3.2.13 on 2022-06-23 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0063_auto_20220623_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makepayment',
            name='renewal_period',
        ),
        migrations.AddField(
            model_name='makepayment',
            name='assigned_duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makepayment',
            name='credit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='makepayment',
            name='install_period',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='makepayment',
            name='install_range',
            field=models.CharField(default='Day(s)', max_length=100),
        ),
        migrations.AddField(
            model_name='makepayment',
            name='subscription_expiry',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
