# Generated by Django 3.2.13 on 2022-06-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0066_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='amount_paid',
            new_name='credit',
        ),
    ]
