# Generated by Django 3.2.13 on 2022-06-24 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0067_rename_amount_paid_balance_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(blank=True, null=True)),
                ('member', models.CharField(max_length=100, null=True)),
                ('profile_url', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('email_address', models.EmailField(max_length=500, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('account_type', models.IntegerField(blank=True, null=True)),
                ('member_type', models.IntegerField(blank=True, null=True)),
                ('branch', models.IntegerField(blank=True, null=True)),
                ('recently_paid', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
