# Generated by Django 3.2.13 on 2022-06-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0071_alter_count_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='makepayment',
            name='outstanding_balance',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
