# Generated by Django 3.2.13 on 2022-06-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0073_auto_20220625_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='makepayment',
            name='donation_name',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
