# Generated by Django 3.2.13 on 2022-06-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0075_auto_20220625_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='public-uploads/')),
                ('organization_name', models.CharField(max_length=100)),
                ('donation_name', models.CharField(max_length=100)),
                ('target_amount', models.IntegerField(default=0, null=True)),
                ('amount_paid', models.IntegerField(default=0, null=True)),
                ('purpose', models.CharField(max_length=500, null=True)),
                ('contact', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=500, null=True)),
                ('website', models.URLField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_name', models.CharField(max_length=100)),
                ('target_amount', models.IntegerField(default=0, null=True)),
                ('amount_paid', models.IntegerField(default=0, null=True)),
                ('donors_name', models.CharField(max_length=500, null=True)),
                ('contact', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=500, null=True)),
                ('country', models.CharField(max_length=500, null=True)),
                ('currency', models.CharField(max_length=500, null=True)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='amount_received',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='target_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
