# Generated by Django 3.2.13 on 2022-06-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0076_auto_20220627_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicDonation',
        ),
        migrations.DeleteModel(
            name='PublicPayments',
        ),
    ]
