# Generated by Django 3.2.13 on 2022-06-28 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0082_remove_publicpayments_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalamount',
            name='date_paid',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='totalpayments',
            name='date_paid',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='totalamount',
            name='member',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='totalpayments',
            name='member',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
