# Generated by Django 3.2.13 on 2022-06-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0083_auto_20220628_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalamount',
            old_name='date_paid',
            new_name='date_created',
        ),
    ]
