# Generated by Django 3.2.13 on 2022-06-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0085_assignpaymentduration_deactivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicdonation',
            name='payment_url',
            field=models.URLField(default='google.com', null=True),
        ),
    ]
