# Generated by Django 3.2.13 on 2022-06-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0086_publicdonation_payment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_name', models.CharField(max_length=100)),
                ('target_amount', models.IntegerField(default=0, null=True)),
                ('amount_received', models.IntegerField(default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterInvoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=100)),
                ('member_category', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('subgroup', models.CharField(max_length=100)),
                ('items_amount', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField(default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('fee_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.feedescription')),
                ('fee_items', models.ManyToManyField(to='superuser.FeeItems')),
                ('fee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.feetype')),
            ],
        ),
    ]
