# Generated by Django 3.2.13 on 2022-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0087_printerdonation_printerinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='subscriber',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
