# Generated by Django 3.2.13 on 2022-09-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0089_currency_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('duration', models.CharField(max_length=100, null=True)),
                ('renewing_days', models.IntegerField(max_length=100, null=True)),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('subscription_expiry', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
