# Generated by Django 3.2.13 on 2022-11-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0090_subcriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignpaymentduration',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignpaymentduration',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignperiod',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignperiod',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedescription',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedescription',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feeitems',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feeitems',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feetype',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feetype',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makepayment',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makepayment',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printerdonation',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printerdonation',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printerinvoice',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='printerinvoice',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicdonation',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicdonation',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicpayments',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicpayments',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcriptionpayment',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcriptionpayment',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='totalamount',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='totalamount',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='totalpayments',
            name='client',
            field=models.CharField(default='Lord', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='totalpayments',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcriptionpayment',
            name='renewing_days',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
