# Generated by Django 3.2.13 on 2022-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0091_auto_20221112_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignpaymentduration',
            name='client',
        ),
        migrations.RemoveField(
            model_name='assignpaymentduration',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='client',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='makepayment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='makepayment',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='members',
            name='client',
        ),
        migrations.RemoveField(
            model_name='totalamount',
            name='client',
        ),
        migrations.RemoveField(
            model_name='totalamount',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='totalpayments',
            name='client',
        ),
        migrations.RemoveField(
            model_name='totalpayments',
            name='client_id',
        ),
        migrations.AddField(
            model_name='assignpaymentduration',
            name='member_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='member_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makepayment',
            name='member_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='totalamount',
            name='member_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='totalpayments',
            name='member_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
    ]
