# Generated by Django 3.2.13 on 2022-11-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0092_auto_20221114_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignpaymentduration',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makepayment',
            name='client_id',
            field=models.CharField(default='1', max_length=100, null=True),
        ),
    ]
