# Generated by Django 3.2.13 on 2022-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0101_servicefee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='makepayment',
            name='amount_left',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
