# Generated by Django 3.2.13 on 2022-12-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0102_makepayment_amount_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='makepayment',
            name='fee_description_value',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makepayment',
            name='fee_type_value',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
    ]
