# Generated by Django 3.2.13 on 2022-12-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0103_auto_20221203_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='branch',
            field=models.CharField(default='Main Branch', max_length=100, null=True),
        ),
    ]
