# Generated by Django 3.2.13 on 2022-12-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0104_activitylog_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignpaymentduration',
            name='auto',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
