# Generated by Django 3.2.13 on 2022-12-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0105_assignpaymentduration_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='about',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='digital_address',
            field=models.CharField(default='GA-1234-567', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='facebook',
            field=models.CharField(default='@akwaaba.com', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='instagram',
            field=models.CharField(default='@akwaaba.com', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='location',
            field=models.CharField(default='Accra', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='postal_address',
            field=models.CharField(default='P.O Box 1', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='services',
            field=models.CharField(default='None', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='telegram',
            field=models.CharField(default='233000000000', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='twitter',
            field=models.CharField(default='@akwaaba.com', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='website',
            field=models.CharField(default='https://google.com', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='whatsapp',
            field=models.CharField(default='233000000000', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedescription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feeitems',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='printerinvoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
