# Generated by Django 3.2.13 on 2023-02-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0106_auto_20221217_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflinePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='1', max_length=100, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('member_category', models.CharField(max_length=100, null=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('subgroup', models.CharField(max_length=100, null=True)),
                ('total', models.FloatField(blank=True, default=0.0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='1', max_length=100, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('member_category', models.CharField(max_length=100, null=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('subgroup', models.CharField(max_length=100, null=True)),
                ('total', models.FloatField(blank=True, default=0.0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='totalamount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='totalpayments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
