# Generated by Django 3.2.13 on 2023-02-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0109_auto_20230221_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpayments',
            name='branch',
            field=models.CharField(default='Main Branch', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicpayments',
            name='group',
            field=models.CharField(default='Zone 12', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicpayments',
            name='member_category',
            field=models.CharField(default='Staff', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicpayments',
            name='subgroup',
            field=models.CharField(default='Group A', max_length=100, null=True),
        ),
    ]
