# Generated by Django 3.2.13 on 2023-02-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0110_auto_20230221_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalpayments',
            old_name='date_paid',
            new_name='date_created',
        ),
    ]
