# Generated by Django 3.2.13 on 2023-02-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0111_rename_date_paid_totalpayments_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='makepayment',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='offlinepayments',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onlinepayments',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
