# Generated by Django 3.2.13 on 2023-02-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0113_alter_makepayment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
