# Generated by Django 3.2.13 on 2023-02-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0114_alter_assignpaymentduration_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='member_type',
            field=models.CharField(default='individual', max_length=100),
        ),
    ]
